training_pipeline_config:
  pipeline_name: visa
  artifact: artifacts

data_ingestion_config:
  dataset_download_url: url(s3,url,github)
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test